.macos_saas_runners:
  tags:
    - saas-macos-medium-m1
  image: macos-12-xcode-14
  before_script:
    - echo "started by ${GITLAB_USER_NAME}"

stages:
  - build

build-job:
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  extends:
    - .macos_saas_runners
  stage: build
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - pip3 install codemagic-cli-tools
    - ls -la
    - keychain initialize
    - keychain use-login
    - app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) 
      --platform=IOS 
      --type=IOS_APP_STORE 
      --issuer-id=$APP_STORE_CONNECT_ISSUER_ID 
      --key-id=$APP_STORE_CONNECT_KEY_IDENTIFIER 
      --private-key=@file:AuthKey.p8 
      --certificate-key=@file:cert_key 
      --create
    - keychain add-certificates
    - xcode-project use-profiles
    - flutter packages pub get
    - find . -name "Podfile" -execdir pod install \;
    - flutter build ipa --export-options-plist=$HOME/export_options.plist
    - keychain use-login