name: IOS Release

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  ARCHITECTURE: ios

jobs:
  build-ios-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'widealpha/cave-forum'
          token: ${{ secrets.CAVE_REPO_TOKEN }}
          ref: ${{ github.ref_name }} #使用tag的name进行check

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.3"
          channel: 'stable'

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Get current tag annotation
        id: tag_data
        uses: ericcornelissen/git-tag-annotation-action@v2

      - name: Read flutter and version build name
        id: read_version
        run: |
          versionName=$(grep -oE '^version:[[:space:]]*[0-9]+\.[0-9]+\.[0-9]+' pubspec.yaml | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "versionName=$versionName" >> "$GITHUB_OUTPUT"

      - name: Download IOS App store connection private key
        id: app_store_connect_key
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: AuthKey.p8
          encodedString: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY_BASE64 }}

      - name: Download IOS App store certificate key
        id: app_store_certificate_key
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: cert_key
          encodedString: ${{ secrets.APP_STORE_CERTIFICATE_KEY_BASE64 }}

      - name: Install the Apple certificate and provisioning profile
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY_PATH: ${{ steps.app_store_connect_key.outputs.filePath }}
          APP_STORE_CERTIFICATE_KEY_PATH: ${{ steps.app_store_certificate_key.outputs.filePath }}
        run: |
          pip3 install codemagic-cli-tools
          keychain initialize
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
            --platform=IOS \
            --type=IOS_APP_STORE \
            --issuer-id=${{ env.APP_STORE_CONNECT_ISSUER_ID }} \
            --key-id=${{ env.APP_STORE_CONNECT_KEY_IDENTIFIER }} \
            --private-key=@file:${{ env.APP_STORE_CONNECT_PRIVATE_KEY_PATH }} \
            --certificate-key=@file:${{ env.APP_STORE_CERTIFICATE_KEY_PATH }} \
            --create
          keychain add-certificates

      - name: Start IOS release build ${{ github.ref_name }}
        run: |
          xcode-project use-profiles
          flutter packages pub get
          find . -name "Podfile" -execdir pod install \;
          flutter build ipa --export-options-plist=$HOME/export_options.plist

      - name: Upload IOS release to artifacts
        uses: actions/upload-artifact@v4
        id: upload_to_artifact
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: cave-${{ github.ref_name }}-${{ env.ARCHITECTURE }}-release
          path: build/ios/ipa/*.ipa
          retention-days: 3

      - name: Upload ipa to testflight
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY_PATH: ${{ steps.app_store_connect_key.outputs.filePath }}
        run: |
          app-store-connect publish \
            --issuer-id=${{ env.APP_STORE_CONNECT_ISSUER_ID }} \
            --key-id=${{ env.APP_STORE_CONNECT_KEY_IDENTIFIER }} \
            --private-key=@file:${{ env.APP_STORE_CONNECT_PRIVATE_KEY_PATH }} \
            --path=build/ios/ipa/*.ipa \
            --locale=zh-Hans \
            --whats-new='${{ steps.tag_data.outputs.git-tag-annotation }}' \
            --version-string=${{ steps.read_version.outputs.versionName }} \
            --platform=IOS \
            --release-type=MANUAL \
            --testflight

      - name: Reset to default login key chain
        run: |
          keychain use-login
